spring:
  datasource:
    url: jdbc:mysql://123.206.118.12:3306/mkframework?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Fww198509!
    driverClassName: com.mysql.jdbc.Driver
