spring:
  datasource:
    url: jdbc:mysql://123.206.118.12:3306/mkframework?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Fww198509!
    driverClassName: com.mysql.jdbc.Driver

mk:
  encrypt: true
  encryptAlgo: des
  key: 6B@5b7a8434